export const SEARCH_REPO = 'SEARCH_REPO';
export const SEARCH_REPO_SUCCESS = 'SEARCH_REPO_SUCCESS';

export const GET_PR_LIST = 'GET_PR_LIST';
export const GET_PR_SUCCESS = 'GET_PR_SUCCESS';
export const GET_PR_LIST_SUCCESS = 'GET_PR_LIST_SUCCESS';
